name: CI
# Run on master, tags, or any pull request
on:
  schedule:
    - cron: '0 1 * * *'  # Daily at 1 AM UTC (7 PM CST)
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # We test the latest 64-bit julia release for all 3 major platforms
      matrix:
        version:
          - 1
          - 'lts'
          - 'pre'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
        include:
          # Add a 1.0 job just to make sure we still support it
          - os: ubuntu-latest
            version: 1.0.5
            arch: x64
          # Add a Windows 1.5 job because of https://github.com/JuliaLang/julia/issues/40237
          - os: windows-latest
            version: 1.5
            arch: x64
          # Add a 32-bit job to ensure we don't have any 64-bit specific logic
          - os: ubuntu-latest
            version: 1
            arch: x86
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - run: |
          git config --global user.name name
          git config --global user.email email
          git config --global github.user username
      - run: |
          julia --project=docs -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();
            include("docs/make.jl");'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}